---
title: Resources
timezone: EST
collections:
  categories:
    title: Categories
    output: true
  linkList:
    title: Link List
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: posts
- scope:
    path: ''
    type: linkList
  values:
    layout: link-list
    permalink: "/:categories/:path/"
    list:
    - title: ''
      link: ''
email: dustin@delatore.me
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl: ''
url: http://example.com
twitter_username: whos_dustin
github_username: whosdustin
markdown: kramdown
permalink: "/:title/"
